const CONFIG = {
    introTitle: 'gửi chị My đáng ju của iemmm',
    introDesc: `ở xa nên không biết chúc chị thế nào cho đặc biệt nên thoii làm cái n cho chị zuii`,
    btnIntro: 'không được chê!!!! ',
    title: 'thấy em có kuteee khoonggg ',
    desc: 'màu đỏ là có màu xanh là khong nha' ',
    btnYes: 'em thích chị hihi <33',
    btnNo: 'ai cho đâu mà không =))):3',
    question:'sao chị đáng iu quá z  😡 ',
    btnReply: 'ấn đại dô điii chị =)))',
    reply: 'chúc chị một năm mới không muộn phiền, không được khóc, không được buồn, kiếm được một người xứng đáng với chị, earn more money hơn =))))',
    mess: 'chị xinh lắm á nha không được tự ti đou em nói tâng bốc em làm kiki =))))',
    messDesc: 'đừng có mà thức trễ nữaaaaa',
    btnAccept: 'phải làm được, phải làm được, phải làm được',
    messLink: 'https://www.facebook.com/linhxinkdeppppp/,
}
